import type { Metadata } from "next";
import { WalletProvider } from "@/contexts/WalletContext";
import { WalletDisplay } from "@/components/wallet";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <WalletProvider>
          <header className="border-b border-gray-200 dark:border-gray-700 px-4 py-3 flex justify-end">
            <WalletDisplay />
          </header>
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
