/**
 * Canonical structured log field names for MyFans.
 *
 * Every log entry MUST include the mandatory fields; optional fields SHOULD be
 * included when the value is available in the current execution context.
 *
 * Mandatory
 * ---------
 * @field timestamp  – ISO-8601 UTC, added by the Winston timestamp() format.
 * @field level      – Winston log level string (info | warn | error | debug | verbose).
 * @field message    – Human-readable description of the event.
 * @field service    – Constant identifier for this application ("myfans-backend").
 *
 * Optional / context-dependent
 * ----------------------------
 * @field context       – NestJS module / class name (e.g. "SubscriptionsService").
 * @field correlationId – Propagated from the inbound X-Correlation-ID header.
 * @field requestId     – Per-request UUID generated by the request-context middleware.
 * @field userId        – Authenticated user's Stellar public key (when available).
 * @field method        – HTTP verb (GET, POST, …).
 * @field url           – Request path (no query string to avoid leaking PII).
 * @field statusCode    – HTTP response status code.
 * @field latencyMs     – Request / job duration in milliseconds.
 * @field event         – Machine-readable event name (e.g. "job.started").
 * @field error         – Error message string (never a full stack trace at warn+).
 * @field trace         – Stack trace string (error level only).
 * @field data          – Arbitrary redacted payload (must pass through redact()).
 */
export const LOG_FIELDS = {
  // Mandatory
  TIMESTAMP: 'timestamp',
  LEVEL: 'level',
  MESSAGE: 'message',
  SERVICE: 'service',

  // Optional
  CONTEXT: 'context',
  CORRELATION_ID: 'correlationId',
  REQUEST_ID: 'requestId',
  USER_ID: 'userId',
  METHOD: 'method',
  URL: 'url',
  STATUS_CODE: 'statusCode',
  LATENCY_MS: 'latencyMs',
  EVENT: 'event',
  ERROR: 'error',
  TRACE: 'trace',
  DATA: 'data',
} as const;

export type LogFieldKey = (typeof LOG_FIELDS)[keyof typeof LOG_FIELDS];

/** The service name injected into every log entry. */
export const SERVICE_NAME = 'myfans-backend';
